name: CI test to run SCM ccpp_prebuild script

on: [push, pull_request, workflow_dispatch]

jobs:
  build-linux:

    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Initialize submodules
      run: git submodule update --init --recursive

    - name: Set up Python 3.8.5
      uses: actions/setup-python@v5
      with:
        python-version: 3.8.5

    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH

    - name: Update system packages
      run: sudo apt-get update

    - name: Run ccpp_prebuild.py
      run: |
        mkdir -p /home/runner/work/ccpp-scm/ccpp-scm/scm/bin/ccpp/physics/physics/
        ./ccpp/framework/scripts/ccpp_prebuild.py --config ccpp/config/ccpp_prebuild_config.py
